%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
# https://carnegierobotics.com/support-updates/
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 381.62
Camera.fy: 381.62
Camera.cx: 360.5
Camera.cy: 360.5

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 720
Camera.height: 720

# Camera frames per second 
Camera.fps: 30.0

# stereo baseline times fx
# is the horizontal focal length (in pixels) multiplied by the baseline (in meters).
#Camera.bf: 36.488 Bom
#Camera.bf: 37.185
Camera.bf: 38

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
# ThDepth can be safely set around 50.
ThDepth: 50

# Deptmap values factor (what pixel value in the depth image corresponds to 1m?)
# DepthMapFactor is a scale factor that multiplies the input depthmap (if needed) if you are using a RGB-D camera.
# For RGB-D inputs only. For some datasets (e.g. TUM) the depthmap values are scaled.
# DepthMapFactor: 0.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 12
ORBextractor.minThFAST: 11

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
#Viewer.KeyFrameSize: 0.05
#Viewer.KeyFrameLineWidth: 1
#Viewer.GraphLineWidth: 0.9
#Viewer.PointSize: 2
#Viewer.CameraSize: 0.08
#Viewer.CameraLineWidth: 3
#Viewer.ViewpointX: 0
#Viewer.ViewpointY: -0.7
#Viewer.ViewpointZ: -1.8
#Viewer.ViewpointF: 500